package com.mfsys.comm.util;

public enum FieldNameConstant implements DBFieldNameConstant {

    PTR_TRANCODE("ptrTrancode", "PTR_TRANCODE"),
    PTR_TRANDESC("ptrTrandesc", "PTR_TRANDESC"),
    PDT_DOTYCODE("pdtdotycode", "PDT_DOTYCODE"),
    PDT_DOTYTYPE("pdtdotytype", "PDT_DOTYTYPE"),
    POR_ORGACODE("porOrgacode", DBFieldNameConstant.POR_ORGACODE),
    SUS_USERCODE("susUsercode", "SUS_USERCODE"),
    SUS_NAME("susName", "SUS_NAME"),
    PCR_CURRCODE("pcrCurrcode", "PCR_CURRCODE"),
    PCR_CURRBASE("pcrCurrbase", "PCR_CURRBASE"),
    SGT_GNTRAMTFC("sgtGntramtfc", "SGT_GNTRAMTFC"),
    PLC_LOCACODE("plcLocacode", "PLC_LOCACODE"),
    SGT_GNTRVALUEDATE("sgtGntrvaluedate", "SGT_GNTRVALUEDATE"),
    MBM_BKMSNUMBER("mbmBkmsnumber", "MBM_BKMSNUMBER"),
    MBM_BKMSCLOSED("mbmBkmsclosed", "MBM_BKMSCLOSED"),
    MBM_BKMSCLOSEDBY("mbmBkmsclosedby", "MBM_BKMSCLOSEDBY"),
    MBM_BKMSTITLE("mbmBkmstitle", "MBM_BKMSTITLE"),
    MBM_CHARGE_EXEMPTED("mbmChargeExempted", "MBM_CHARGE_EXEMPTED"),
    DMP_PRODCODE("dmpProdcode", "DMP_PRODCODE"),
    MLT_LNTRPRINCIPAL("mltLntrprincipal", "MLT_LNTRPRINCIPAL"),
    MLT_LNTRINTEREST("mltLntrinterest", "MLT_LNTRINTEREST"),
    MLT_LNTRPENALTY("mltLntrpenalty", "MLT_LNTRPENALTY"),
    SGT_GNTRNARRATION("sgtGntrnarration", "SGT_GNTRNARRATION"),
    BLA_LNACFINANCEDAMTFC("blaLnacfinancedamtfc", "BLA_LNACFINANCEDAMTFC"),
    BLA_LNACDISBURSEMENTFC("blaLnacdisbursementfc", "BLA_LNACDISBURSEMENTFC"),
    DMP_PRODDESC("dmpProddesc", "DMP_PRODDESC"),
    PER_ERATRATEACT("perEratrateact", "PER_ERATRATEACT"),
    PCR_CURRDESC("pcrCurrdesc", "PCR_CURRDESC"),
    PLC_LOCADESC("plcLocadesc", "PLC_LOCADESC"),
    PLC_LOCASHORT("plcLocashort", "PLC_LOCASHORT"),
    PLC_LOCATYPE("plcLocatype", "PLC_LOCATYPE"),
    PRG_REGNCODE("prgRegncode", "PRG_REGNCODE"),
    PLC_OPENDATE("plcOpendate", "PLC_OPENDATE"),
    BRANCH_DATA("branchStep", "BRANCH_STEP"),
    CHARGES_BIFURCATION("chargesBifurcation", "CHARGES_BIFURCATION"),
    CMP_CUSTCODE("cmpCustcode", "CMP_CUSTCODE"),
    MARKED_STATUS("markedStatus", "MARKED_STATUS"),
    CMP_CUSTSEX("cmpcustsex", "CMP_CUSTSEX"),
    CMP_GRPOUPCODE("cmpGrpoupcode", "CMP_GRPOUPCODE"),
    PCC_CSCGCODE("pccCscgcode", "PCC_CSCGCODE"),
    PFS_FUSOID("pfsFusoid", "PFS_FUSOID"),
    PAT_AMTYCODE("patAmtycode", "PAT_AMTYCODE"),
    BLA_LNMBSHARE_APPROVED("blaLnmbshareApproved", "BLA_LNMBSHARE_APPROVED"),
    BLA_ASSOCIATECUSTOMER("blaAssociatecustomer", "BLA_ASSOCIATECUSTOMER"),
    CMP_CUSTCODE_GRP("cmpCustcodeGrp", "CMP_CUSTCODE_GRP"),
    CORRELATION_CUSTCODE("correlationCustcode", "CORRELATION_CUSTCODE"),
    CMP_COMPANYCODE("cmpCompanycode", "CMP_COMPANYCODE"),
    CMP_COMPANYCODE_REF("cmpCompanycodeRef", "CMP_COMPANYCODE_REF"),
    CMP_COMPANYNAME("cmpCompanyname", "CMP_COMPANYNAME"),
    CMP_JOINTCUSTCODE("cmpJointcustcode", "CMP_JOINTCUSTCODE"),
    CMP_JOINTNAME("cmpJointName", "CMP_JOINTNAME"),
    ACC_ATTORTYPE("accAttortype", "ACC_ATTORTYPE"),
    ACC_ATTORTYPE_B("accAttortypeB", "ACC_ATTORTYPE_B"),
    ACC_JOINT_STATUS("accJointStatus", "ACC_JOINT_STATUS"),
    ACC_JOINT_STATUS_B("accJointStatusB", "ACC_JOINT_STATUS_B"),
    PIT_JOINTIDENVALUE("pitJoinidenvalue", "PIT_JOINTIDENVALUE"),
    PIT_JOINTIDENCODE("pitJoinidenCode", "PIT_JOINTIDENCODE"),
    PAS_ACSTCODE("pasAcstcode", "PAS_ACSTCODE"),
    BDA_DPACBLOCKAMT("bdaDpacblockamt", "BDA_DPACBLOCKAMT"),
    BDA_DPACPROFITACCRUEDAMTFC("bdaDpacprofitaccruedamtfc", "BDA_DPACPROFITACCRUEDAMTFC"),
    MLS_LNSHTYPE("mlsLnshtype", "MLS_LNSHTYPE"),
    MLS_LNSHINSTNO("mlsLnshinstno", "MLS_LNSHINSTNO"),
    MLS_LNSHDUEDATE("mlsLnshduedate", "MLS_LNSHDUEDATE"),
    MLS_LNSHPRINCIPAL("mlsLnshprincipal", "MLS_LNSHPRINCIPAL"),
    MLS_LNSHINTEREST("mlsLnshinterest", "MLS_LNSHINTEREST"),
    BLA_LNAPPROVEDAMOUNTFC("blaLnapprovedamountfc", "BLA_LNAPPROVEDAMOUNTFC"),
    BLA_LNACAPPROVEDATE("blaLnacapprovedate", "BLA_LNACAPPROVEDATE"),
    CLOSING_DETAILS("closingBalanceDetails", ""),
    WORKFLOWREFNUM("workFlowRefNum", "workFlowRefNum"),
    PIN_LENGTH("4", "pinLength"),
    POR_ORGADESC("porOrgadesc", "POR_ORGADESC"),
    POR_ORGASHORT("porOrgashort", "POR_ORGASHORT"),
    POR_ORGAREGDATE("porOrgaregdate", "POR_ORGAREGDATE"),
    POR_ORGALOGO("porOrgalogo", "POR_ORGALOGO"),
    POR_ORGAREPORTLOGO("porOrgareportlogo", "POR_ORGAREPORTLOGO"),
    POR_TRANINTEGRALVALUE("porTranintegralvalue", "POR_TRANINTEGRALVALUE"),
    POR_TRANPRECISIONVALUE("porTranrprecisionvalue", "POR_TRANPRECISIONVALUE"),
    POR_TRANROUNDTYPE("porTranroundtype", "POR_TRANROUNDTYPE"),
    POR_ROUNDINGMODETRANSACTION("porRoundingmodetransactions", "POR_ROUNDINGMODETRANSACTION"),
    POR_ORGAEXPDATE("porOrgaexpdate", "POR_ORGAEXPDATE"),
    POR_ORGAFAX("porOrgafax", "POR_ORGAFAX"),
    POR_ADRSLNDPHONE("porAdrslndphone", "POR_ADRSLNDPHONE"),
    POR_ORGAADDRESSLINE1("por_orgaaddressline1", "POR_ORGAADDRESSLINE1"),
    POR_ORGAADDRESSLINE2("por_orgaaddressline2", "POR_ORGAADDRESSLINE2"),
    POR_ORGAWEBSITE("porOrgawebsite", "POR_ORGAWEBSITE"),
    POR_ORGACODE_ENTRY("porOrgacodeEntry", "POR_ORGACODE_ENTRY"),
    POR_ACTIVE("porActive", "POR_ACTIVE"),
    SUS_USERNAME("susUsername", "SUS_USERNAME"),
    SUS_PASSWORD("susPassword", "SUS_PASSWORD"),
    SUS_USERCELLNO("susUsercellno", "SUS_USERCELLNO"),
    SUL_LEVELCODE("sulLevelCode", "SUL_LEVELCODE"),
    SUL_DESC("sulDesc", "SUL_DESC"),
    SUL_STATUS("sulStatus", "SUL_STATUS"), SUS_MULTILOGIN("susMultilogin", "SUS_MULTILOGIN"),
    SUS_HOMELOCATION("susHomelocation", "SUS_HOMELOCATION"),
    SUS_ACTIVE("susActive", "SUS_ACTIVE"),
    SUS_SIGNLOG("susSignlog", "SUS_SIGNLOG"),
    USER_DATA("userStep", "USER_STEP"),
    ROLE_DATA("roleStep", "ROLE_STEP"),
    PCA_GLACDEBIT("pcaGlacdebit", "PCA_GLACDEBIT"),
    PCA_GLACCREDIT("pcaGlaccredit", "PCA_GLACCREDIT"),
    PCH_CHRGCODE("pchChrgcode", "PCH_CHRGCODE"),
    PCH_CHRGDESC("pchChrgdesc", "PCH_CHRGDESC"),
    PET_EVENTCODE_POST("petEventcodePost", "PET_EVENTCODE_POST"),
    PET_EXRTCODE("petExrtcode", "PET_EXRTCODE"),
    PER_ERATDATE("perEratdate", "PER_ERATDATE"),
    PLT_LOCATYPEDESC("pltLocatypedesc", "PLT_LOCATYPEDESC"),
    CMP_CREATEDBY("cmpCreatedby", "CMP_CREATEDBY"),
    PLC_LOCACODE_ENTRY("PLC_LOCACODE_ENTRY", "PLC_LOCACODE_ENTRY"),
    POR_ORGATIMEZONE("porOrgatimezone", "POR_ORGATIMEZONE"),
    POR_ORGAUTCTIMEZONE("porOrgautctimezone", "POR_ORGAUTCTIMEZONE"),
    POR_IBANFORMAT("porIbanformat", "POR_IBANFORMAT"),
    PLC_LOCATIMEZONE("plcLocatimezone", "PLC_LOCATIMEZONE"),
    PLC_ACTIVE("plcActive", "PLC_ACTIVE"),
    PCA_GLACCODE("pcaGlaccode", "PCA_GLACCODE"),
    SGT_GNTRDATE("sgtGntrdate", "SGT_GNTRDATE"),
    SGT_GNTRCANCELLED("sgtGntrcancelled", "SGT_GNTRCANCELLED"),
    SGT_GNTRAMT("sgtGntramt", "SGT_GNTRAMT"),
    SUB_BRANCH("subBranch", "SUB_BRANCH"),
    PFS_ACNTDATEFROM("pfs_acntdatefrom", "PFS_ACNTDATEFROM"),
    PFS_ACNTDATETO("pfs_acntdateto", "PFS_ACNTDATETO"),
    PFS_ACNTDESC("pfs_acntdesc", "PFS_ACNTDESC"),
    BGP_GLPRCOMPANYDATE("bgpGlprcompanydate", "BGP_GLPRCOMPANYDATE"),
    BGP_GLPRCOMPANYTIMEZONE("bgpGlprcompanytimezone", "BGP_GLPRCOMPANYDATE"),
    BGP_GLPROPERATIONCLOSE("bgpGlproperationclose", "BGP_GLPROPERATIONCLOSE"),
    BGP_GLPRNEXTDATE("bgpGlprnextdate", "BGP_GLPRNEXTDATE"),
    PCO_CLDSTATUS("pcoCldstatus", "PCO_CLDSTATUS"),
    PCO_CLDSHADOWED("pcoCldshadowed", "PCO_CLDSHADOWED"),
    PCO_CLDBATCHPROCESS("pcoCldbatchprocess", "PCO_CLDBATCHPROCESS"),
    PCO_CLDBATCHPROCESSFIRSTSTEP("pcoCldbatchprocessfirststep", "PCO_CLDBATCHPROCESSFIRSTSTEP"),
    PCO_CLDERRMESSAGE("pcoClderrmessage", "PCO_CLDERRMESSAGE"),
    BLA_LNAPPLIEDAMOUNTFC("blaLnappliedamountfc", "BLA_LNAPPLIEDAMOUNTFC"),
    BLA_LNACINTERESTRATE("blaLnacinterestrate", "BLA_LNACINTERESTRATE"),
    PCD_CORDCODE("pcdCordcode", "PCD_CORDCODE"),
    PPO_PURPCODE("ppoPurpcode", "PPO_PURPCODE"),
    OLD_PCD_CORDCODE("oldPcdCordcode", "OLD_PCD_CORDCODE"),
    NEW_PCD_CORDCODE("newPcdCordcode", "NEW_PCD_CORDCODE"),
    PCD_CORDCOMMENT("pcdCordcomment", "PCD_CORDCOMMENT"),
    SGT_GNTRNUMBER("sgtGntrnumber", "SGT_GNTRNUMBER"),
    SGT_GNTRTRANLINK("sgtGntrtranlink", "SGT_GNTRTRANLINK"),
    SGT_GNTRCREATEDAT("sgtGntrcreatedat", "SGT_GNTRCREATEDAT"),
    BTA_BOOKINGAMOUNT("btaBookingamount", "BTA_BOOKINGAMOUNT"),
    BTA_DURATION("btaDuration", "BTA_DURATION"),
    PFM_FMODCODE("pfmFmodcode", "PFM_FMODCODE"),
    PRO_RLOVCODE("proRlovcode", "PRO_RLOVCODE"),
    PTM_TMETCODE("ptmTmetcode", "PTM_TMETCODE"),
    PTM_TMETDESC("ptmTmetdesc", "PTM_TMETDESC"),
    PLC_CHARGECALCRATE("plcChargecalcrate", "PLC_CHARGECALCRATE"),
    SVH_VCHDUPDATETIMESTAMP("svhVchdupdatetimestamp", "SVH_VCHDUPDATETIMESTAMP"),
    SVH_VCHDFLDCOMB("svhVchdfldcomb", "SVH_VCHDFLDCOMB"),
    SVH_VCHDVALCOMBDESC("svhVchdvalcombdesc", "SVH_VCHDVALCOMBDESC"),
    PAA_TAAUTIMESTAMP("paaTaautimestamp", "PAA_TAAUTIMESTAMP"),
    MBM_BKMSBALANCE("mbmBkmsbalance", "MBM_BKMSBALANCE"),
    MBM_BKMSUNAUTHDRBALANCE("mbmBkmsunauthdrbalance", "MBM_BKMSUNAUTHDRBALANCE"),
    MBM_BKMSUNAUTHCRBALANCE("mbmBkmsunauthcrbalance", "MBM_BKMSUNAUTHCRBALANCE"),
    CURRENT_AMOUNT("currentAmount", "CURRENT_AMOUNT"),
    CURRENCY_DENOMINATION_DETIAL("currencyDenominationDetail", "currencyDenominationDetail"),
    CLOSE_OPERATION_DATA("closeOperationData", "closeOperationData"),
    PCA_GLACOPITEM("pcaGlacopitem", "PCA_GLACOPITEM"),
    PCT_CALCODE("pctCalcode", "PCT_CALCODE"),
    NODE_ID("nodeId", "NODE_ID"),
    SVV_VCVRREFNO("svvVcvrrefno", "SVV_VCVRREFNO"),
    PIT_INSTCODE("pitInstcode", "PIT_INSTCODE"),
    MIT_INSTCODE("mitInstcode", "MIT_INSTCODE"),
    MIS_INSEBOOKNO("misInsebookno", "MIS_INSEBOOKNO"),
    PIS_INSTCODE("pisInstcode", "PIS_INSTCODE"),
    PIN_INVSCODE("pinInvscode", "PIN_INVSCODE"),
    MIS_INSERANGEFROM("misInserangefrom", "MIS_INSERANGEFROM"),
    MIS_INSERANGETO("misInserangeto", "MIS_INSERANGETO"),
    MIS_INSERECVDATE("misInserecvdate", "MIS_INSERECVDATE"),
    MIS_INSEISSUEACNTDATE("misInseissueacntdate", "MIS_INSEISSUEACNTDATE"),
    PPM_PYMDCODE("ppmPymdcode", "PPM_PYMDCODE"),
    CRDR_CODE("crdrcode", "CRDRCODE"),
    ACCOUNT_TRA_NO("pcaGlaccodeAc", "ACCOUNT_TRANSFER_NO"),
    MBM_BKMSNUMBER_REF("mbmBkmsnumberRef", "MBM_BKMSNUMBER_REF"),
    PLC_LOCACODE_REF("plcLocacodeRef", "PLC_LOCACODE_REF"),
    MBM_BKMSNUMBER_REF_OPERATIONAL("mbmBkmsnumberRefOperational", "MBM_BKMSNUMBER_REF_OPERATIONAL"),
    DMP_PRODCODE_REF("dmpProdcodeRef", "DMP_PRODCODE_REF"),
    DMP_PRODCODE_REF_OPERATIONAL("dmpProdcodeRefOperational", "DMP_PRODCODE_REF_OPERATIONAL"),
    DMP_PRODGRCEINTEREST("dmpProdgrceinterest", "DMP_PRODGRCEINTEREST"),
    DMP_LNACGRACEPRINCIPLE("dmpLnacgraceprinciple", "DMP_LNACGRACEPRINCIPLE"),
    BLN_RESTRUCTUREPRINCIPALAMT("blnRestructureprincipalamt", "BLN_RESTRUCTUREPRINCIPALAMT"),
    BLA_LNACDISBURSEMENTDATE("bla_lnacdisbursementdate", "BLA_LNACDISBURSEMENTDATE"),
    PROCESS_COMPLETED("processCompleted", "processCompleted"),
    MIS_INSELOST("MIS_INSELOST", "MIS_INSELOST"),
    BATCH_USERCODE("@_CREATEUSER", "@_CREATEUSER"),
    SGT_GNTRCREATEAT("sgtGntrcreateat", "SGT_GNTRCREATEAT"),
    CMP_ACCOUNT_TITLE_FL("cmpAccountTitleFl", "CMP_ACCOUNT_TITLE_FL"),
    CMP_ACCOUNT_TITLE_LF("cmpAccountTitleLf", "CMP_ACCOUNT_TITLE_LF"),
    BN_CS_IT_IDENTIFIER("bnCsItIdentifier", "BN_CS_IT_IDENTIFIER"),
    CIT_IDENVALUE("citIdenValue", "CIT_IDENVALUE"),
    CIT_IDENVALUE_2("citIdenValue2", "CIT_IDENVALUE_2"),
    CIT_IDENEXPIRYDATE("citIdenexpirydate", "CIT_IDENEXPIRYDATE"),
    PIT_IDENVALUE("pitIdenvalue", "PIT_IDENVALUE"),
    PIT_IDENCODE("pitIdenCode", "PIT_IDENCODE"),
    PIT_IDENCODE_2("pitIdenCode2", "PIT_IDENCODE_2"),
    PIT_PRIMARYIDENCODE("pitPrimaryidencode", "PIT_PRIMARYIDENCODE"),
    PIT_IDENEXPIRYDATE("pitIdenexpirydate", "PIT_IDENEXPIRYDATE"),
    PED_INSTALLMENT("pedInstallment", "PED_INSTALLMENT"),

    TO_DATE("todate", "TO_DATE"),
    FROM_DATE("fromdate", "FROM_DATE"),
    MBM_BKMSLOANCYCLE("mbmBkmsloancycle", "MBM_BKMSLOANCYCLE"),
    DEBIT_AMOUNT("totalDebitAmount", "totalDebitAmount"),
    CREDIT_AMOUNT("totalCreditAmount", "totalCreditAmount"),
    PBD_BANKCODE("pbdBankcode", "PBD_BANKCODE"),
    PBB_BRANCHCODE("pbbBranchcode", "PBB_BRANCHCODE"),


    BTA_AUTOROLLED("BtaAutorolled", "BTA_AUTOROLLED"),

    BLN_RESTRUCTUREADDITIONALAMT("blnRestructureadditionalamt", "BLN_RESTRUCTUREADDITIONALAMT"),
    CMP_BLACKLISTED("cmpBlacklisted", "CMP_BLACKLISTED"),
    CMP_BLOCKED("cmpBlocked", "CMP_BLOCKED"),
    CMP_FREEZED("cmpFreezed", "CMP_FREEZED"),
    CMP_FREEZETYPE("cmpFreezetype", "CMP_FREEZETYPE"),
    BGP_FRACTIONALSCALE("bgpFractionalscale", "BGP_FRACTIONALSCALE"),
    BGP_BLACKLISTSETUP("bgpBlacklistsetup", "BGP_BLACKLISTSETUP"),
    BGP_BIOMETRICSETUP("bgpBiometricsetup", "BGP_BIOMETRICSETUP"),
    BGP_PRIMARYIDENEXPIRYVALIDATION("bgpIdenexpiryvalidation", "BGP_IDENEXPIRYVALIDATION"),
    PLC_CHARGECALCRATE_ACCOUNT("plcChargecalcrateAccount", "PLC_CHARGECALCRATE_ACCOUNT"),
    DST_STIERVALUE("dstStiervalueAccount", "DST_STIERVALUE"),
    DST_STIERVALUE_ACCOUNT("dstStiervalue", "DST_STIERVALUE_ACCOUNT"),
    BLA_ASSOCIATENAME("blaAssociatename", "BLA_ASSOCIATENAME"),
    ANR_ACNRCODE("anrAcnrcode", "ANR_ACNRCODE"),
    BLG_CUSTCODE("blgCustcode", "BLG_CUSTCODE"),
    BLG_CUSTNAME("blgCustname", "BLG_CUSTNAME"),
    BLG_LOCACODE("blgLocacode", "BLG_LOCACODE"),
    BDA_LIENREASON("bdaLienreason", "BDA_LIENREASON"),
    PREV_BLOCKAMT("prevBlockedamt", "PREV_BLOCKAMT"),
    BDA_LIENDATE("bdaLiendate", "BDA_LIENDATE"),
    BDA_LIENTIME("bdaLientime", "BDA_LIENTIME"),
    MBM_LOAN_LIEN_ALLOWED("mbmLoanLienAllowed", "MBM_LOAN_LIEN_ALLOWED"),
    MBM_BKMSNUMBER_LOAN_REF("mbmBkmsnumberLoanRef ", "MBM_BKMSNUMBER_LOAN_REF"),
    MBM_BKMSTITLE_LOAN_REF("mbmBkmstitleLoanRef ", "MBM_BKMSTITLE_LOAN_REF"),
    BLA_LNACMATURITYDATE_LOAN_REF("blaLnacmaturitydateLoanRef ", "BLA_LNACMATURITYDATE_LOAN_REF"),

    RATE_AMOUNT("rateAmount", "RATE_AMOUNT"),


    PLC_ALLOWED_LOCA("plcallowedloca", "PLC_ALLOWED_LOCA"),
    PLC_AMOUNTFROM("plcamountfrom", "PLC_AMOUNTFROM"),
    PLC_AMOUNTTO("plcamountto", "PLC_AMOUNTTO"),
    PLC_CHARGECALCRATE_PRODUCT("plcchargecalcrateproduct", "PLC_CHARGECALCRATE_PRODUCT"),

    //Online Banking
    CMP_CUSTPASSWORD("cmpCustpassword", "CMP_CUSTPASSWORD"),
    CMP_CUSTSTATUS("cmpCuststatus", "CMP_CUSTSTATUS"),
    CMP_CUSTSTATUSDATE("cmpCuststatusdate", "CMP_CUSTSTATUSDATE"),
    CMP_CUSTLASTLOGIN("cmpCustlastlogin", "CMP_CUSTLASTLOGIN"),
    PCT_CSTYCODE("pctCstycode", "PCT_CSTYCODE"),
    CMP_FIRSTNAME("cmpFirstname", "CMP_FIRSTNAME"),
    CMP_LASTNAME("cmpLastname", "CMP_LASTNAME"),
    CMP_FATHERNAME("cmpFathername", "CMP_FATHERNAME"),
    CMP_CUSTDATEBIRTH("cmpCustdatebirth", "CMP_CUSTDATEBIRTH"),
    BLG_IDENCODE("blgIdencode", "BLG_IDENCODE"),
    BLG_IDENVALUE("blgIdenvalue", "BLG_IDENVALUE"),
    CMP_IDENVALUE("cmpIdenvalue", "CMP_IDENVALUE"),
    CMP_IDENCODE("cmpIdencode", "CMP_IDENCODE"),
    PAD_ADRSMOBPHONE("padAdrsmobphone", "PAD_ADRSMOBPHONE"),
    CMP_NAME("cmpName", "CMP_NAME"),
    PAD_ADRSEMAIL("padAdrsemail", "PAD_ADRSEMAIL"),
    PAD_ADRSCORRESPONDENCE("padAdrscorrespondence", "PAD_ADRSCORRESPONDENCE"),
    OCB_BENEFICIARYVERIFIED("ocbBeneficiaryverified", "OCB_BENEFICIARYVERIFIED"),
    OCB_BENEFICIARYVERIFYDATE("ocbBeneficiaryverifydate", "OCB_BENEFICIARYVERIFYDATE"),
    PRC_CLASSIFICATION("prcClassification", "PRC_CLASSIFICATION"),
    OTD_TRANSACTIONPOSTED("otdTransactionposted", "OTD_TRANSACTIONPOSTED"),
    OTD_TRANSACTIONPOSTDATE("otdTransactionpostdate", "OTD_TRANSACTIONPOSTDATE"),
    OTD_TRANSACTIONID("otdTransactionid", "OTD_TRANSACTIONID"),

    ORGANIZATION("organization", "ORGANIZATION"),
    LOCATION("location", "LOCATION"),
    CURRENCY("currency", "CURRENCY"),
    GLOBALPARAMETER("globalparameter", "GLOBALPARAMETER"),
    PCA_GLACODE_DEBIT("pcaGlacodeDebit", "PCA_GLACODE_DEBIT"),
    PCA_GLACODE_CREDIT("pcaGlacodeCredit", "PCA_GLACODE_CREDIT"),
    PLC_APPLYACCRUAL("plcApplyaccrual", "PLC_APPLYACCRUAL"),
    PFS_ACNTSTATUS("pfsAcntstatus", "PFS_ACNTSTATUS"),
    PRO_RLOVTONEWACCOUNT("proRlovtonewaccount", "PRO_RLOVTONEWACCOUNT"),
    BBS_BATCHSTATUS("bbsBatchstatus", "BBS_BATCHSTATUS"),
    BBS_BATCHAMT("bbsBatchamt", "BBS_BATCHAMT"),
    BLA_LNACGRACEPRINCIPLE("blaLnacgraceprinciple", "BLA_LNACGRACEPRINCIPLE"),
    BLA_LNACTOTALDURATION("blaLnactotalduration", "BLA_LNACTOTALDURATION"),
    BLA_LNACEFFECTIVEDATE("blaLnaceffectivedate", "BLA_LNACEFFECTIVEDATE"),
    BN_MS_LS_LOANSCHEDULE("BN_MS_LS_LOANSCHEDULE", "BN_MS_LS_LOANSCHEDULE"),
    BLC_SERIALNO("blcSerialno", "BLC_SERIALNO"),
    CMP_CUSTCODE_REF("cmpCustcodeRef", "CMP_CUSTCODE_REF"),
    SYNC_STATUS("syncStatus", "SYNC_STATUS"),
    MLS_LNSHINSTTOTAL("mlsLnshinsttotal", "MLS_LNSHINSTTOTAL"),
    SYSTEM_ORGA("SYSTEM_ORGA", "SYSTEM_ORGA"),
    PLC_SUBLOCACODE("plcSublocacode", "PLC_SUBLOCACODE"),
    PLC_SUBLOCADESC("plcSublocadesc", "PLC_SUBLOCADESC"),
    ISC_AUTO_REVERSAL("iscAutoReversal", "ISC_AUTO_REVERSAL"),
    MBM_NOTIFICATIONSERVICE("mbmNotificationService", "MBM_NOTIFICATIONSERVICE"),
    SERIAL_NO("serialNo", "SERIAL_NO"),
    NOTIFICATION_STATUS("notificationStatus", "NOTIFICATION_STATUS"),
    MESSAGE("Message", "MESSAGE"),
    SGT_GNTRDRCR("sgtGntrdrcr", "SGT_GNTRDRCR"),
    PIT_JOINTCUSTCODE("pitJoincustcode", "PIT_JOINTCUSTCODE"),
    PCO_CTRYCODE("pcoCtrycode", "PCO_CTRYCODE"),
    UDF3("prgntmUdf3", "PR_GN_TM_UDF3"),
    UDF1("prgntmUdf1", "PR_GN_TM_UDF1"),
    UDF4("prgntmUdf4", "PR_GN_TM_UDF4"),
    PFS_ACNTYEAR("pfsAcntyear", "PFS_ACNTYEAR"),

    //cdr
    CDR_REASON("cdrReason", "cdr_reason"),
    LIMIT("limit", "LIMIT"),
    MBM_BKMSFREEZETYPE("mbmBkmsfreezetype", "MBM_BKMSFREEZETYPE"), MBM_BKMSFREEZE("mbmBkmsfreeze", "mbm_Bkmsfreeze"),
    MBM_BKMSCREDITFREEZE("mbmBkmscreditfreeze", "MBM_BKMSCREDITFREEZE"), MBM_BKMSDEBITFREEZE("mbmBkmsdebitfreeze", "MBM_BKMSDEBITFREEZE"),
    MBM_REGULATORYRESTRICTION("mbmRegulatoryRestriction", "MBM_REGULATORYRESTRICTION"),
    MBM_ACCBLOCKED("mbmAccblocked", "mbm_Accblocked"),
    CMP_ACCOUNTYPE("cmpAccounttype", "CMP_ACCOUNTTYPE"), MBM_ACTIVITYPOOL("mbmActivitypool", "MBM_ACTIVITYPOOL"),
    PCT_COLTCATCODE("pctColtcatcode", "PCT_COLTCATCODE"), PCT_COLTCODE("pctColtcode", "PCT_COLTCODE"),
    MBM_BKMSZAKATEXEMPTION("mbm_bkmszakatexemption", "MBM_BKMSZAKATEXEMPTION"), PRS_RESNCODE("prsResncode", "PRS_RESNCODE"),
    IBAN_COUNTRY("ibanCountry", "C"),
    IBAN_CHECKSUM("ibanChecksum", "X"),
    IBAN_BANK("ibanBank", "B"),
    IBAN_RESERVE("ibanReserve", "R"),
    IBAN_BRANCH("ibanBranch", "L"),
    IBAN_PRODUCT("ibanProduct", "P"),
    IBAN_ACCOUNT("ibanAccount", "A"),
    MBM_BKMSNUMBER_IBAN("mbmBkmsnumberIban", "MBM_BKMSNUMBER_IBAN"),
    MBM_IBANACTIVATION("mbmIbanActivation", "MBM_IBANACTIVATION"),

    PRC_ATTORCODE("prcAttorcode", "PRC_ATTORCODE"),
    PRC_ATTORDESC("pcrAttordesc", "PRC_ATTORDESC"),
    KYC_RENEWAL_DATE("kycRenewalDate", "KYC_RENEWAL_DATE"),
    IS_DEDUCTION("isDeduction", "IS_DEDUCTION"),
    SGT_GNTRUDF3("sgtGntrudf3", "SGT_GNTRUDF3"),


    POR_PASSREMINDDAYS("porPassreminddays", "POR_PASSREMINDDAYS"),
    POR_PASSEXPIRYDURATION("porPassexpiryduration", "POR_PASSEXPIRYDURATION"),
    PCT_BACKUPTYPE("pctBackuptype", "PCT_BACKUPTYPE"),

    //national and international blacklist upload for FMFI
    CMP_FULLNAME("cmpFullname", "CMP_FULLNAME"),
    CMP_FIRSTNAME_EN("cmpFirstnameEn", "CMP_FIRSTNAME_ENGLISH"),
    CMP_LASTNAME_EN("cmpLastnameEn", "CMP_LASTNAME_EN"),
    CMP_FULLNAME_EN("cmpFullnameEn", "CMP_FULLNAME_EN"),
    CMP_COMPANYNAME_ENG("cmpCompanyEng", "CMP_COMPANYNAME_ENG"),

    ACCOUNT_TYPE("accountType", "ACCOUNT_TYPE"), STATUS_CODE("statusCode", "status_code"), TRANSACTION_NO("tranNo", "TRAN_NO"),

    //for Notification Module
    PNS_NOTIFTYPE("pnsNotiftype", "PNS_NOTIFTYPE"), PNS_TEMPTCODE("pnsTemptcode", "PNS_TEMPTCODE"), PNS_NOTIFDESC("pnsNotifdesc", "PNS_NOTIFDESC"),
    ATTRIBUTES("attributes", "ATTRIBUTES"), PARAMETER_LIST("paramList", "PARAM_LIST"), VOUCHER_NO("voucherNo", "VOUCHER_NO"),

    // BankerCheque
    BANKCHQREF_NUMBER("bankerChequeRefNo", "BANKCHQREF_NUMBER"), BNK_CHQLEAF_NUMBER("bnkChqLeafNumber", "BNK_CHQLEAF_NUMBER"),

    //classificationType
    CLASSIFICATION_TYPE("classificationType", "CLASSIFICATION_TYPE"),

    MIRGE("MIRGE", "MIRGE"), PENSEMBLE("PENSEMBLE", "PENSEMBLE"),
    FORMAT("RSA", "RSA"),
    MBM_BKMSBALAMOUNT("mbmBkmsbalamount", "MBM_BKMSBALAMOUNT"),
    MBM_BKMSBALDATE("mbmBkmsbaldate", "MBM_BKMSBALDATE"),
    BAL_TYPE("balType", "BAL_TYPE");


    private final String variableName;
    private final String dbFieldName;

    FieldNameConstant(String variableName, String dbFieldName) {
        this.variableName = variableName;
        this.dbFieldName = dbFieldName;
    }

    public String getVariableName() {
        return variableName;
    }

    public String getDbFieldName() {
        return dbFieldName;
    }

}
