server:
  port: 8082

spring:
  application:
    name: UCO-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/uco
    #    username: root
    #    password: root
    url: jdbc:mysql://${UCO_SQL_DB_MACHINE_IP}/uco
    username: ${UCO_SQL_DB_USER}
    password: ${UCO_SQL_DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000 # 7 days